services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Topdata\TopdataProductReviewReminderSW6\:
        resource: '../../{Command,Controller,Service,Subscriber,ScheduledTask}'